### ISSUE TITLE
unable to select [4]: Interrupted system call

### ISSUE THREAD

**Issue by Furgas** [qxsch/WorkerPool#10]
When using automatic respawn a PHP warning is triggered in SimpleSocket.php:66, originating from WorkerPool.php:637:

> socket_select(): unable to select [4]: Interrupted system call

Based on [this answer from SO](https://stackoverflow.com/a/2938156/170403), I guess that `pcntl_alarm` is interferring with `socket_select`.

**Comment by qxsch** [comment]
Thank you for your ticket. The issue should be fixed.

**Comment by Furgas** [comment]
I guess it won't remove the warning. I will later try an approach with silencing operator on `socket_select` and use `socket_last_error` to check for this particular error (`SOCKET_EINTR`), and only then repeat the `socket_select` (clearing the error first, with `socket_clear_error`). I'm not yet sure what to do when the error is a different one - maybe manually trigger a warning with a message obtained from `socket_strerror`, to preserve the original behaviour.
