### ISSUE TITLE
All workers were gone. message in PHP 7.3

### ISSUE THREAD

**Issue by HcErwin** [qxsch/WorkerPool#14]
It crashes in the `getNextFreeWorker` method of the `Workerpool.php` file. I tried to debug a bit, but not sure if this has to do with PHP 7.3 specific. I upgraded PHP form 7.2 to 7.3 with Homebrew on my MacBookPro yesterday and after that it started. Weirdly enough on Ubuntu I already have it running for some time and didn't seem to have that.

**Comment by qxsch** [comment]
Can you give more info. I cannot reproduce it without more information...

**Comment by HcErwin** [comment]
Strangely, on 2 different MacBook Pro's (2015 and 2018) both was broken until macOS Sierra. Since the macOS Catalina update (with PHP 7.3.11) this issue seems gone. Don't know what changed. Both laptops had nothing fancies custom installed.
