### ISSUE TITLE
No response when testing with PHPUnit

### ISSUE THREAD

**Issue by yuki12321** [qxsch/WorkerPool#17]
I am using qxsch/WorkerPool.
Thanks to you it is very useful. Thank you.

I am using PHPUnit to test where WorkerPool is used.
When the test is run, the results are not displayed.
Perhaps the execution has stopped and is no longer responding.
```
% ./vendor/bin/sail exec laravel.test php artisan test

   PASS  Tests\Unit\ExampleTest
  ✓ that true is true
# (No longer responding)

# (in docker container)
% ps -aux 
root        36  0.8  2.6 142896 52908 pts/0    S+   12:33   0:00 phpunit: Parent
root        37  0.0  1.2 142896 26296 pts/0    S+   12:33   0:00 phpunit: Worker 1 of QXS\WorkerPool\ClosureWorker [free]
# (No change since then)
```
A [Repository](https://github.com/yuki12321/laravel-test-parallel-processing-command) of projects that have been verified to work is temporarily open to the public.
Am I missing something?

**Comment by qxsch** [comment]
Thanks for the feedback.

it seems, that the laravel/sail wrapper might be causing issues.
