### ISSUE TITLE
Documentation: system requirements.

### ISSUE THREAD

**Issue by Beanow** [qxsch/WorkerPool#2]
Glancing over some of the documentation it's not clear to me what the exact requirements are.
Would be nice to include those in the readme/wiki.

**Comment by qxsch** [comment]
hi,

requirements can be seen here:
https://packagist.org/packages/qxsch/worker-pool

```
Requires
php: >=5.3.0
ext-pcntl: *
ext-posix: *
ext-sysvsem: *
ext-sockets: *
```

there is an installation guide in the wiki:
https://github.com/qxsch/WorkerPool/wiki/How-to-install%3F
