### ISSUE TITLE
Unreleased semaphores

### ISSUE THREAD

**Issue by KevenLibcast** [qxsch/WorkerPool#4]
We are using the WorkerPool for asynchronous tasks at work but we encounter a bug we cannot fix by ourselves.

After a while, we see this error message:

```
Warning: sem_get(): failed for key 0x24ffdec4: No space left on device in /home/[..]/vendor/qxsch/worker-pool/src/Semaphore.php on line 99
```

The `ipcs -s` command confirms that a bunch of semaphores are created, since several weeks, but not released.

It seems that semaphores created by the WorkerPool may not be released after that.
When does it occur, and how can we fix this?

Thank you for your work.

**Comment by KevenLibcast** [comment]
Some details on the issues : in our worker, we use Predis and Monolog with a Sentry Handler.
So maybe WorkerPool cannot work nicely with one ot these library?

**Comment by qxsch** [comment]
hi,

Semaphores should be destroyed whenever you no longer need it. (by calling `$semaphore->destroy()` in the parent)
Usually, the semaphore will be created by filename. So it should always be the same. (hence there will be no urgent need to auto-destroy it, because just one semaphore will be opened.)

**In case you are using many instances or many different installation paths, you have to open your own ids**
**in case you open your own ids you will also have to destroy them on your own.**

Please do create any ressources after the workerpool->create method.
For more information also look at: https://github.com/qxsch/WorkerPool/wiki/How-to-use-the-pool%3F

**Comment by qxsch** [comment]
By default FTOK will be used, that should always result in the same number:
https://github.com/qxsch/WorkerPool/blob/master/src/Semaphore.php#L62
https://github.com/qxsch/WorkerPool/blob/master/src/Semaphore.php#L80
https://github.com/qxsch/WorkerPool/blob/master/src/Semaphore.php#L90

To use a dedicated ID, use:
`$s=new Semaphore(); $s->create(ftok(__FILE__, 's')); $workerpool->setSemaphore($s);`
or even more static (just for testing):
`$s=new Semaphore(); $s->create(123456);  $workerpool->setSemaphore($s);`

Remember, that semaphores should be destroyed whenever you no longer need it. (by calling $semaphore->destroy() in the parent)

**Comment by KevenLibcast** [comment]
It is, indeed, a problem with semaphores which were not destroyed from the parent.
Here is the example from the `README`, modified to illustrate the problem (an uncatched Exception is thrown from the parent to simulate a failure in a component - Redis in our case but it can be anything in real world scripts) :

``` php
<?php

require_once __DIR__.'/vendor/autoload.php';

$wp=new \QXS\WorkerPool\WorkerPool();
$wp->setWorkerPoolSize(4)
   ->create(new \QXS\WorkerPool\ClosureWorker(
                        /**
                          * @param mixed $input the input from the WorkerPool::run() Method
                          * @param \QXS\WorkerPool\Semaphore $semaphore the semaphore to synchronize calls accross all workers
                          * @param \ArrayObject $storage a persistent storage for the current child process
                          */
                        function($input, $semaphore, $storage) {
                                echo "[".getmypid()."]"." hi $input\n";
                sleep(10);
                                return $input; // return null here, in case you do not want to pass any data to the parent 
                        }
                )
);


for($i=0; $i<10; $i++) {
        $wp->run($i);
}

sleep(1);
throw new RuntimeException('Simulate failure');

$wp->waitForAllWorkers(); // wait for all workers

foreach($wp as $val) {
        var_dump($val);  // dump the returned values
}
```

Output:

```
keven@bunsen:/tmp$ php test.php 
[13772] hi 0
[13773] hi 1
[13774] hi 2
[13775] hi 3
[13772] hi 4
[13773] hi 5
[13774] hi 6
[13775] hi 7
[13772] hi 8
[13773] hi 9
PHP Fatal error:  Uncaught exception 'RuntimeException' with message 'Simulate failure' in /tmp/test.php:27
Stack trace:
#0 {main}
  thrown in /tmp/test.php on line 27
```

Here is a list of semaphores before:

```
keven@bunsen:~$ ipcs -s

------ Semaphore Arrays --------
key        semid      owner      perms      nsems     
0x56d024f4 262152     keven      666        3         
```

...and after:

```
keven@bunsen:~$ ipcs -s

------ Semaphore Arrays --------
key        semid      owner      perms      nsems     
0x56d024f4 262152     keven      666        3         
0xc5839ed4 294921     keven      666        3         
```

A new semaphore has been created and is not released on script halt.

**Comment by KevenLibcast** [comment]
The problem is that `WorkerPool::destroy()` is not triggered on the parent.
In the example above, I see the `destroy()` method being triggered from 2 workers (why not 4? I don't know) but never from the parent.

If the exception in the parent is catched and the WP is then exited, the `destroy()` method is triggered and the semaphore is deleted after all workers have finished (or have been killed) :

``` php
try {
    throw new RuntimeException('Simulate failure');
} catch (Exception $e) {
    $wp->exitPhp(1);
}
```

**Comment by KevenLibcast** [comment]
Ok I found a workaround to force the `destroy()` method to be triggered on the parent when a uncatched exception is thrown, using `register_shutdown_function()`.

In `WorkerPool::create()`, in the following block of code:

``` php
            } else {
                // WE ARE IN THE PARENT
                socket_close($sockets[0]); // close child socket
                // create the child
                $this->workerProcesses->addFree(new ProcessDetails($processId, new SimpleSocket($sockets[1])));
            }
```

...declare a shutdown function:

``` php
            } else {
                // WE ARE IN THE PARENT
                socket_close($sockets[0]); // close child socket
                // create the child
                $this->workerProcesses->addFree(new ProcessDetails($processId, new SimpleSocket($sockets[1])));
                if (!isset($this->shutdownRegistered)) {
                    register_shutdown_function([$this, 'destroy']);
                    $this->shutdownRegistered = true;
                }
            }
```

The `$this->shutdownRegistered` property is used to register the shutdown only once instead of n times, n being the number of workers.

Doing this, the `destroy()` method is still triggered twice but the first time is always from the parent.
Honestly, I cannot explain that so I prefer not to submit a PR with this code change.

I hope you are able to propose a better way to handle this issue in the light of these tests.

**Comment by qxsch** [comment]
ok, i understand the problem.
This happens whenever the destructor is not being called. Especially, on the following condtions:
- PHP errors, that lead to an immediate exit
- Uncaught exceptions, that lead to an immediate exit

as you have suggested you can do the following as a workarround:
- use a super `try { } catch(Exception $e) { }` block
- use `set_error_handler`, `set_exception_handler` or `register_shutdown_function`

i gonna add, the your `register_shutdown_function` to the workerpool.

Thank a lot for your analysis! :-)

**Comment by qxsch** [comment]
Fixed.
