### ISSUE TITLE
invalid Socket resources

### ISSUE THREAD

**Issue by florisvink** [qxsch/WorkerPool#5]
Hi!

When all jobs are completed and the script is about the complete I get several warnings about invalid socket resources.

```
Warning: socket_last_error(): 420 is not a valid Socket resource /home/[...]/vendor/qxsch/worker-pool/src/SimpleSocket.php 159
Warning: socket_last_error(): 420 is not a valid Socket resource /home/[...]/vendor/qxsch/worker-pool/src/SimpleSocket.php 161
```

All seems to work properly nonetheless.  I run Ubuntu 15 with PHP 5.6.4. 
Any ideas on what the origin of those warnings could be?

Many thanks in advance!

Floris

**Comment by qxsch** [comment]
is it happening in a child? This just means, that the parent died before at least one child.

Check your code.

**Comment by qxsch** [comment]
Closing the issue.
